/// Represents the specific JSON object returned by the `/vip_auto_buy` endpoint
/// when `pay_type` is 2 (WeChat Pay).
/// This model is designed to manually parse the JSON from your backend.
class WeChatPayInfoModel {
  /// The App ID registered on the WeChat Open Platform.
  final String appId;

  /// The Partner ID (Merchant ID) from WeChat Pay.
  final String partnerId;

  /// The Prepay ID generated by WeChat's unified order API.
  final String prepayId;

  /// The package value, typically "Sign=WXPay".
  /// This field is named `package` in the API response and `fluwx` model.
  final String package;

  /// A random string to ensure signature uniqueness.
  final String nonceStr;

  /// A timestamp in seconds since the epoch.
  final int timeStamp;

  /// The signature generated by your backend to secure the transaction.
  final String sign;

  WeChatPayInfoModel({
    required this.appId,
    required this.partnerId,
    required this.prepayId,
    required this.package,
    required this.nonceStr,
    required this.timeStamp,
    required this.sign,
  });

  /// Creates an instance from a JSON map, matching the exact keys from your API.
  factory WeChatPayInfoModel.fromJson(Map<String, dynamic> json) {
    return WeChatPayInfoModel(
      appId: json['appid'] as String,
      partnerId: json['partnerid'] as String,
      prepayId: json['prepayid'] as String,
      // The API returns 'package', which is what the fluwx plugin expects.
      package: json['package'] as String,
      nonceStr: json['noncestr'] as String,
      // The API might return timestamp as an int or a string, this handles both cases.
      timeStamp: json['timestamp'] is String
          ? int.parse(json['timestamp'])
          : json['timestamp'] as int,
      sign: json['sign'] as String,
    );
  }
}